### ISSUE TITLE
Not compiling TS with `npm run dev`

### ISSUE THREAD

**Issue by melalj** [edwinhern/express-typescript-2024#128]
It looks like that the TS code is not being recompiled when there's a change.
Did I miss something?

Here's my workaround:
```
    "dev": "tsc-watch --noClear --onSuccess \"tsx ./dist/index.js\"",
```

**Comment by edwinhern** [comment]
Hey @melalj, just tested and works fine for me. Could you provide more context on what you changed that didn't render.
