### ISSUE TITLE
Add "pino" as a Dependency

### ISSUE THREAD

**Issue by igorlamos** [edwinhern/express-typescript-2024#299]
You're importing [`pino`](https://www.npmjs.com/package/pino) in https://github.com/edwinhern/express-typescript-2024/blob/master/src/server.ts#L4 yet [`package.json`](https://github.com/edwinhern/express-typescript-2024/blob/master/package.json) does not define this dependency.

Seems like it works with some package managers because [`pino`](https://www.npmjs.com/package/pino) is installed as a phantom dependency.

I've been trying it with Rush + PNPM setup where [phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/) "issue" is solved out-of-box, therefore I've found this minor issue.

**Comment by edwinhern** [comment]
Great catch, going to add to new fix.!
