### ISSUE TITLE
Recommendation - use envalid

### ISSUE THREAD

**Issue by Darkmift** [edwinhern/express-typescript-2024#53]
Great template!

I recommend letting envalid handle envirment sanitation and validation.

https://www.npmjs.com/package/envalid

Would be happy to apply & refactor if you interested to explore further.

**Comment by edwinhern** [comment]
Hey @Darkmift,

Just saw your message. I've looked into `envalid` and am currently reviewing its features. I'm open to incorporating it into our project. If you're interested, feel free to contribute directly to the project, and we can review for a merge. Alternatively, I can handle the integration myself. Let me know your preference. :)
