### ISSUE TITLE
Help Wanted: Implementing JWT Authentication for API Routes

### ISSUE THREAD

**Issue by edwinhern** [edwinhern/express-typescript-2024#61]
# Overview
We are planning to integrate JWT-based authentication into our existing API. This feature aims to secure our routes while providing flexibility to exempt certain routes from requiring authentication. Additionally, we want to ensure that our Swagger documentation accurately reflects the authentication requirements for each route.

## Requirements
* Implement JWT authentication middleware that can be easily applied to selected routes.
* Ensure a mechanism is in place to mark certain routes as public (no authentication required) while defaulting to private (authentication required).
* Update our Swagger/OpenAPI documentation to reflect the authentication status of each route, enhancing clarity for API consumers.

## Proposed Solution
I propose the development of a reusable function or middleware that encapsulates the following functionalities:
* JWT Authentication: A middleware that validates JWT tokens for protected routes.
* Route Configuration: Enhance our route setup to include authentication requirements. This could be a flag or setting within the route's configuration.
* Swagger Documentation: Automatically update our OpenAPI documentation based on the route's authentication requirements.

## Example Concept
Here's a conceptual approach to how we might define a route with this new system:

![image](https://github.com/edwinhern/express-typescript-2024/assets/65698930/fcd8449c-beff-476c-b0d7-31d858f57424)

## Contribution Guidelines
* Fork the repository and create a new branch for your feature.
* Write clean, readable, and well-documented code.
* Ensure that existing tests pass and write new tests as necessary to cover the authentication functionality.
* Update the README and any relevant documentation to reflect the changes.
* Submit a pull request with a clear description of the changes and any other relevant information.

## Discussion
I'm open to ideas on how best to implement this feature and would love to collaborate with anyone interested in contributing. If you have experience with JWT authentication or have suggestions on improving this proposal, please feel free to share your thoughts or submit a pull request.

**Comment by Darren120** [comment]
what do u think of using class instead?

pseudo code

`
export type EmptyZodObject = z.ZodObject<{}, 'strip', z.ZodTypeAny, {}, {}>;
export type RouteParams = Record<string, string | string[]> | object;
class AddRouteAndDocument<BaseSchema extends z.AnyZodObject> {
  private name: string;
  private baseSchema: BaseSchema;
  private baseRoute: string;

  private routePaths: string[] = [];
  constructor({
    baseRoute,
    baseSchema,
    name,
  }: {
    name: string;
    baseSchema: BaseSchema;
    baseRoute: `/${string}`;
  }) {
    (this.name = name), (this.baseRoute = baseRoute);
    this.baseSchema = baseSchema;
  }
  public get<ResponseSchema>({
    path,
  }: {
    path: string;
    handler: () => Promise<ResponseSchema>;
  }) {
    if (this.routePaths.includes(path)) {
      console.error(`Duplicate Route path: ${path}`);
      process.exit(1);
    }
    // ... registry stuff ... //
    // ... express stuff ... //
    return this;
  }
  public post() {
    // ... //
  }
}
export const p = new AddRouteAndDocument({
  baseRoute: '/a',
  baseSchema: z.object({}),
  name: 'User',
}).get<{ a: string }>({ path: 'a', handler: async () => {
  return {
    a: 'b'
  }
} }).get(...).post(...);
`

**Comment by edwinhern** [comment]
I like this idea, but I'm wondering if there's a better alternative to generating swagger docs and creating routes with protection.

I am thinking of going away from abstraction and adding a cleaner way to do this. I'm not a fan of using Zod to generate swagger. 

Any recommendations?

**Comment by Darren120** [comment]
@edwinhern I think having Zod is important, it provides single source of truth for schemas. We then use openapi-fetch to generate a client for nextjs/react native/ etc....

I think currently, this boilerplate is amazing, just that handler return type can be anything, but with my sample above, it forces swagger api doc return type to be same as handler return type.

**Comment by edwinhern** [comment]
@Darren120  Not sure I understand. Could you provide example of issue? Right now, swagger doc is receiving return type for each one. 
https://github.com/edwinhern/express-typescript-2024/blob/0f0eb76711da01314f037e22e55fef386e43ca58/src/routes/user/userRouter.ts#L34

**Comment by Darren120** [comment]
not a bug but rather a QOL change. this is super rough code i made in a rush to get a working idea. 

```
class AddRouteAndDocument<BaseSchema extends z.AnyZodObject> {
  private name: string;
  private baseSchema: BaseSchema;
  public readonly baseRoute: string;
  public readonly router = express.Router();
  public readonly registry = new OpenAPIRegistry();

  private routePaths: string[] = [];
  constructor({
    baseRoute,
    baseSchema,
    name,
  }: {
    name: string;
    baseSchema: BaseSchema;
    baseRoute: `/${string}`;
  }) {
    this.name = name;
    this.baseRoute = baseRoute;
    this.baseSchema = baseSchema;
    this.registry.register(name, baseSchema);
  }

  public get<
    ParamsSchema extends z.AnyZodObject,
    QuerySchema extends z.AnyZodObject,
    HeadersSchema extends z.AnyZodObject,
    CookiesSchema extends z.AnyZodObject,
    bodySchema extends ZodRequestBody,
    ResponseSchema extends z.AnyZodObject,
  >({
    requestSchema,
    responseSchema,
    path,
    handler,
  }: {
    path?: `/${string}`;
    requestSchema: {
      params?: ParamsSchema;
      query?: QuerySchema;
      body?: bodySchema;
      cookies?: CookiesSchema;
      headers?: HeadersSchema;
    };

    responseSchema: ResponseSchema;

    handler: ({
      params,
    }: {
      params: { [x in keyof ParamsSchema['_type']]: string };
    }) => Promise<ResponseSchema['_type']>;
  }) {
    const { params } = requestSchema;
    const paramKeys = Object.keys(params?.shape || {});
    // also check dup params and throw
    const parseParams = paramKeys
      ? paramKeys.length === 1
        ? paramKeys[0]
        : paramKeys.join('/:')
      : '';
    const base = `${this.baseRoute}${path ? path : ''}`;
    const pathParsed = `${base}${parseParams ? '/:' + parseParams : ''}`;
    console.log(pathParsed);
    if (this.routePaths.includes(pathParsed)) {
      console.error(`Duplicate Route path: ${pathParsed}`);
      process.exit(1);
    }
    this.routePaths.push(pathParsed);

    this.registry.registerPath({
      method: 'get',
      path:
        base +
          paramKeys.reduce((curr, next) => {
            curr += `/{${next}}`;
            return curr;
          }, '') || '',
      tags: [this.name],
      request: requestSchema,
      responses: createApiResponse(responseSchema, 'Success'),
    });

    this.router.get(
      pathParsed.slice(this.baseRoute.length),
      async (_req: Request, res: Response) => {
        console.log(_req.params);
        const serviceResponse = await userService.findAll();
        handleServiceResponse(serviceResponse, res);
      }
    );

    return this;
  }
}

export const User2 = new AddRouteAndDocument({
  baseRoute: '/usert',
  baseSchema: z.object({}),
  name: 'UserT',
})
  .get({
    responseSchema: z.object({ name: z.string() }),
    requestSchema: {
      params: z.object({
        nameParam: z.string().optional(),
      }),
    },
    handler: async ({ params }) => {
      // typed single source of truth, ts gives params types
      params.nameParam;
      return {
        // ts gives response schema
        name: 'hellos',
      };
    },
  })
  .get({
    responseSchema: z.object({ name: z.string() }),
    path: '/poo',
    requestSchema: {
      params: z.object({
        nameParam: z.string(),
      }),
    },
    handler: async ({ params }) => {
      // typed single source of truth, ts gives params types
      params.nameParam;
      return {
        // ts gives response schema
        name: 'hellos',
      };
    },
  });
```

in openAPIDocumentGenerator add the following
```
  const registry = new OpenAPIRegistry([
    healthCheckRegistry,
    userRegistry,
    User2.registry,
  ]);
```

in server.ts add the following

```
app.use(User2.baseRoute, User2.router);
```

**Comment by Darren120** [comment]
@edwinhern 
https://github.com/Darren120/express-typescript-2024/tree/newGenerator

**Comment by edwinhern** [comment]
I like where this idea is headed, but right now it feels a bit like we're nudging everyone into a specific way of doing things. What if we just provide some cool tools and let them decide how they want to use them in their API designs? That way, everyone gets to create in their own style!

We could create npm package repository to provide the coder to install if they want those helper functions

**Comment by allanice001** [comment]
https://github.com/Decoupled-Saas/api/blob/main/src/registries/authRegistry.ts as a slightly different implementation,
